
sudo: required
dist: trusty
language: cpp

script:
  - mkdir Build && cd Build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
  - cd .. && ./Executables/run-tests

# Handle git submodules by ourselves.
git:
    submodules: false

# Use sed to replace the SSH URL with the public URL, then initialize submodules.
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

matrix:
  include:
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - cmake
            - libboost-all-dev
      env: COMPILER=clang++-3.7
